version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
      POSTGRES_DB: pgvector
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data
