version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
      POSTGRES_DB: pgvector
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgvector"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      CONNECTION_STRING: "postgresql://pgvector:pgvector@db:5432/pgvector"
      SENTENCE_TRANSFORMER_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
